export const selectWaterData = (state) => state.water.waterData;
export const selectWaterIsLoading = (state) => state.water.isLoading;
export const selectTodayWaterData = (state) => state.water.todayWaterData;
export const selectIsLoading = (state) => state.water.isLoading;
export const selectError = (state) => state.water.error;
export const selectNotes = (state) => state.water.waterVolumes;
export const selectStats = (state) => state.water.stats;
export const selectPercent = (state) => state.water.percentage;
export const selectWaterVolumeSum = (state) => state.water.waterVolumeSum;
